server:
  port: 8081
spring:
  application:
    name: spring-boot-file-upload-download

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB  # Threshold after which files are written to disk.
      max-file-size: 200MB  # Max file size
      max-request-size: 215MB  # Max Request Size

  datasource:
    url: jdbc:mysql://localhost:3306/file_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect